objects/Mulesoft_Application__c.object
<CustomObject>
    <fields>
        <fullName>Application_Name__c</fullName>
        <label>Application Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Environment__c</fullName>
        <defaultValue>&quot;SO&quot;</defaultValue>
        <label>Current Environment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_URL__c</fullName>
        <label>Job URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story_Id__c</fullName>
        <formula>CASESAFEID(User_Story_Task__r.copado__User_Story__r.Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>User Story Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mulesoft Application</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Mulesoft Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mulesoft Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Mulesoft_Deployment__c.object
<CustomObject>
    <fields>
        <fullName>Application_Name__c</fullName>
        <label>Application Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <label>Environment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Id__c</fullName>
        <label>Job Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mulesoft_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mulesoft Application</label>
        <referenceTo>Mulesoft_Application__c</referenceTo>
        <relationshipLabel>Mulesoft Deployments</relationshipLabel>
        <relationshipName>Mulesoft_Deployments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>copado__User_Story__c</referenceTo>
        <relationshipLabel>Mulesoft Deployments</relationshipLabel>
        <relationshipName>Mulesoft_Deployments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mulesoft Deployment</label>
    <nameField>
        <label>Mulesoft Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mulesoft Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JenkinsCallout.cls
public class JenkinsCallout {
    
@InvocableMethod(label='Callout to Jenkins')    
public static void makePostCallout(List<string> MAid) {
conductCallout(MAid[0]);
    }
    
@future( callout=true )
public static void conductCallout(String MAid) {
        Mulesoft_Application__c MA = [SELECT Id, Job_URL__c,Application_Name__c,Version__c,Current_Environment__c,User_Story_Id__c from Mulesoft_Application__c MA WHERE Id = : MAid];
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(MA.Job_URL__c);
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json;charset=UTF-8');
        HttpResponse response = http.send(request);
        // Parse the JSON response
        if (response.getStatusCode() != 201) {
            System.debug('The status code returned was not expected: ' +
                response.getStatusCode() + ' ' + response.getStatus());
        } else {
            System.debug(response.getHeader('Location'));
			String locId = response.getHeader('Location');
            String environment = MA.Current_Environment__c;
            if(environment.contains('SO')){environment='DEV';}
            else{if(environment.contains('DEV')){environment='INT';} 
                 else{
                   if(environment.contains('INT')){environment='QA';}
                     else{if(environment.contains('QA')){environment='PRD';}}
                 }  
                }
            String MDName = 'Deployment for: ' + MA.Application_Name__c+', '+MA.Version__c;
			Mulesoft_Deployment__c MD = new Mulesoft_Deployment__c(Name=MDName, Job_Id__c=locId, User_Story__c=MA.User_Story_Id__c,Status__c='Pending', Start_Date__c=system.now(),Environment__c=environment,Mulesoft_Application__c=MA.Id,Application_Name__c=MA.Application_Name__c,Version__c=MA.Version__c);
            insert MD;
        }
    }    
}